# Name of your application. Used to uniquely configure containers.
service: rails-takeyuwebinc

# Name of the container image.
image: takeyuweb/rails-takeyuwebinc

# Deploy to these servers.
servers:
  web:
    - www-takeyuweb-co-jp
  job:
    hosts:
      - www-takeyuweb-co-jp
    cmd: bin/rails solid_queue:start

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# If using something like Cloudflare, it is recommended to set encryption mode 
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption. 
proxy: 
  ssl: false
  host: takeyuweb.co.jp
  # kamal-proxy connects to your container over port 80, use `app_port` to specify a different port.
  app_port: 3000
  healthcheck:
    path: /up
  forward_headers: true

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: takeyuweb

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD
# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
# env:
#   clear:
#     DB_HOST: 192.168.0.2
#   secret:
#     - RAILS_MASTER_KEY
env:
  clear:
    AWS_REGION: ap-northeast-1
    TZ: "Asia/Tokyo"
  secret:
    - RAILS_MASTER_KEY
    - TAKEYUWEBINC_DATABASE_URL

# Use a different ssh user than root
# ssh:
#  user: ubuntu

# Configure builder setup.
builder:
  arch: amd64
  args:
    RUBY_VERSION: 3.3.5

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
#
# aliases:
#   shell: app exec --interactive --reuse "bash"

# kamalに作成を任せると root になり書き込みできないので、先に作成して Dockerfile で指定した uid / gid にしておく
# mkdir -p /srv/kamal/rails-takeyuwebinc-storage
# chown 1000:1000 /srv/kamal/rails-takeyuwebinc-storage
volumes:
  - "/srv/kamal/rails-takeyuwebinc-storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
asset_path: /rails/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Use accessory services (secrets come from .kamal/secrets).
#
# accessories:
#   db:
#     image: mysql:8.0
#     host: 192.168.0.2
#     port: 3306
#     env:
#       clear:
#         MYSQL_ROOT_HOST: '%'
#       secret:
#         - MYSQL_ROOT_PASSWORD
#     files:
#       - config/mysql/production.cnf:/etc/mysql/my.cnf
#       - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
#     directories:
#       - data:/var/lib/mysql
#   redis:
#     image: redis:7.0
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data
accessories:
  postgres:
    image: postgres:17
    host: www-takeyuweb-co-jp
    port: 5432
    env:
      clear:
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "takeyuwebinc_production"
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
